### ISSUE TITLE
error creating qr code

### ISSUE THREAD

**Issue by killmyspan** [navopw/whatsapp-chatgpt#13]
Error: Cannot find module 'qrcode-terminal'
Require stack:
- C:\Users\Ron Rull\Downloads\Compressed\whatsapp-chatgpt-master\src\index.ts
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1039:15)
    at Function.Module._load (node:internal/modules/cjs/loader:885:27)
    at Module.require (node:internal/modules/cjs/loader:1105:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at C:\Users\Ron Rull\Downloads\Compressed\whatsapp-chatgpt-master\src\index.ts:2:16
    at ViteNodeRunner.directRequest (file:///C:/Users/Ron%20Rull/AppData/Local/npm-cache/_npx/f2342a4b64a2bc92/node_modules/vite-node/dist/client.mjs:308:11)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at ViteNodeRunner.cachedRequest (file:///C:/Users/Ron%20Rull/AppData/Local/npm-cache/_npx/f2342a4b64a2bc92/node_modules/vite-node/dist/client.mjs:156:14)
    at ViteNodeRunner.executeFile (file:///C:/Users/Ron%20Rull/AppData/Local/npm-cache/_npx/f2342a4b64a2bc92/node_modules/vite-node/dist/client.mjs:133:12)
    at CAC.run (file:///C:/Users/Ron%20Rull/AppData/Local/npm-cache/_npx/f2342a4b64a2bc92/node_modules/vite-node/dist/cli.mjs:64:5) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\Ron Rull\\Downloads\\Compressed\\whatsapp-chatgpt-master\\src\\index.ts'
  ]
}

**Comment by navopw** [comment]
Execute `npm install` before starting the bot.

This will fix your missing module.
