### ISSUE TITLE
Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'LegacyPhoneFeatures')

### ISSUE THREAD

**Issue by hardik-a-joshi** [navopw/whatsapp-chatgpt#25]
heaving the following error with it :

C:\wamp64\www\whatsapp-chatgpt\node_modules\whatsapp-web.js\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:221
            throw new Error('Evaluation failed: ' + helper_js_1.helper.getExceptionMessage(exceptionDetails));
                  ^

Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'LegacyPhoneFeatures')
    at __puppeteer_evaluation_script__:13:76
    at ExecutionContext._evaluateInternal (C:\wamp64\www\whatsapp-chatgpt\node_modules\whatsapp-web.js\node_modules\puppeteer\src\common\ExecutionContext.ts:273:13)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at ExecutionContext.evaluate (C:\wamp64\www\whatsapp-chatgpt\node_modules\whatsapp-web.js\node_modules\puppeteer\src\common\ExecutionContext.ts:140:12)
    at Client.initialize (C:\wamp64\www\whatsapp-chatgpt\node_modules\whatsapp-web.js\src\Client.js:267:9)

Node.js v18.13.0

**Comment by yjdaoudi** [comment]
Same error on my side with Node.js v19.6.0

**Comment by gustavo-rddi** [comment]
same issue with Node.js v18.12.1

**Comment by navopw** [comment]
This is fixed on the newest version of whatsapp-chatgpt!

Check the newest version, this project now works with OPENAI_API_KEY and not EMAIL & PASSWORD anymore.

You can create a API Key here: https://platform.openai.com/account/api-keys

Also check the latest README: https://github.com/navopw/whatsapp-chatgpt/blob/master/README.md
