### ISSUE TITLE
Automation can't proceed to login due to recaptcha

### ISSUE THREAD

**Issue by mohammed-althaf-h** [navopw/whatsapp-chatgpt#4]
As instructed the chrome opens and enters the email but due to reCAPTCHA the code won't proceed
![image](https://user-images.githubusercontent.com/50052789/208276261-4e8cdd38-6437-4d40-853e-70274c32596b.png)

**Comment by navopw** [comment]
You have to solve the captcha by yourself and then click on Login. The Automation will then fill out the password.

That's how I remember it.

**Comment by mohammed-althaf-h** [comment]
But it's doesn't wait until we clear that CAPTCHA

**Comment by bhavyadamani** [comment]
Facing same error: auto-fill of reCaptcha does not work. please help to fix it. @navopw  thanks

    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at ViteNodeRunner.directRequest (file:///C:/Users/Bhavya.Damani/AppData/Local/npm-cache/_npx/f2342a4b64a2bc92/node_modules/vite-node/dist/client.mjs:289:5)
    at ViteNodeRunner.cachedRequest (file:///C:/Users/Bhavya.Damani/AppData/Local/npm-cache/_npx/f2342a4b64a2bc92/node_modules/vite-node/dist/client.mjs:149:14)
    at ViteNodeRunner.executeFile (file:///C:/Users/Bhavya.Damani/AppData/Local/npm-cache/_npx/f2342a4b64a2bc92/node_modules/vite-node/dist/client.mjs:126:12)
    at CAC.run (file:///C:/Users/Bhavya.Damani/AppData/Local/npm-cache/_npx/f2342a4b64a2bc92/node_modules/vite-node/dist/cli.mjs:678:5) {
  statusCode: 401
}

**Comment by navopw** [comment]
For me it actually works now, please update to the latest version of this project.

Check this video: https://streamable.com/bz2qzd

(No sensitive information in this video 😄)
