### ISSUE TITLE
invalid email

### ISSUE THREAD

**Issue by cojarbi** [navopw/whatsapp-chatgpt#9]
HI,

Im getting an invalid email when starting. env is created and contains the credentials with the valid email for the openai account.

**Comment by navopw** [comment]
Whats the exact error you get (in the console)?

**Comment by DigitalDicast** [comment]
I Have the same issue.

    const error = new ChatGPTError("ChatGPT invalid email");
                    ^

ChatGPTError: ChatGPT invalid email
    at new ChatGPTAPIBrowser (file:///C:/Users/Andres/whatsapp-chatgpt/node_modules/chatgpt/src/chatgpt-api-browser.ts:102:21)
    at C:\Users\Andres\whatsapp-chatgpt\src\index.ts:10:13
    at ViteNodeRunner.directRequest (file:///C:/Users/Andres/AppData/Local/npm-cache/_npx/f2342a4b64a2bc92/node_modules/vite-node/dist/client.mjs:308:5)
    at ViteNodeRunner.cachedRequest (file:///C:/Users/Andres/AppData/Local/npm-cache/_npx/f2342a4b64a2bc92/node_modules/vite-node/dist/client.mjs:156:14)
    at ViteNodeRunner.executeFile (file:///C:/Users/Andres/AppData/Local/npm-cache/_npx/f2342a4b64a2bc92/node_modules/vite-node/dist/client.mjs:133:12)
    at CAC.run (file:///C:/Users/Andres/AppData/Local/npm-cache/_npx/f2342a4b64a2bc92/node_modules/vite-node/dist/cli.mjs:64:5) {
  statusCode: 401
}

**Comment by Nick-1357** [comment]
I got the same issue as well

**Comment by Benjas333** [comment]
Same, I just copied and pasted the exact email and password, I'm pretty sure they're right. Idk why I got that error.

**Comment by navopw** [comment]
Hm, thats weird.

I will release a version soon which works with an OpenAI API Key instead of Email and Password.

**Comment by Nick-1357** [comment]
Actually there is a way to bypass that. If u replace the email and password with ur account details instead of process.env.***, you can still get it running.

**Comment by Ahelion** [comment]
Same error for me. Do you have the fix in some branch?

**Comment by thober1987** [comment]
> Actually there is a way to bypass that. If u replace the email and password with ur account details instead of process.env.***, you can still get it running.

I have the same issue. Can you show in detail how you achieve this?

**Comment by navopw** [comment]
Check the newest version, this project now works with OPENAI_API_KEY and not EMAIL & PASSWORD anymore.

You can create a API Key here: https://platform.openai.com/account/api-keys

Also check the latest README: https://github.com/navopw/whatsapp-chatgpt/blob/master/README.md
